### ISSUE TITLE
model processing process and loss function

### ISSUE THREAD

**Issue by dana-niu** [ictnlp/SAMMT#1]
Hello, can you tell me which py file this model processing process and loss function are written in?

**Comment by Christina0717** [comment]
Thanks for your attention. The model processing process is in [fairseq/models/multimodal_transformer.py](https://github.com/ictnlp/SAMMT/blob/main/fairseq/models/multimodal_transformer.py), while loss functions are in [fairseq/criterions/label_smoothed_cross_entropy.py](https://github.com/ictnlp/SAMMT/blob/main/fairseq/criterions/label_smoothed_cross_entropy.py).

**Comment by dana-niu** [comment]
Thank you very much for your reply and I wish you all the best.



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/04/2024 14:59 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ictnlp/SAMMT] model processing process and loss function (Issue #1) |

Thanks for your attention. The model processing process is in fairseq/models/multimodal_transformer.py, while loss functions are in fairseq/criterions/label_smoothed_cross_entropy.py.
