### ISSUE TITLE
garbled codes

### ISSUE THREAD

**Issue by dana-niu** [ictnlp/SAMMT#2]
Hello, I'm running "bash train_mmt.sh" and there is garbled code.

PermissionError: [WinError 32] □□һ□□□□□□□□□□ʹ□ô□□ļ□□□□□□□□޷□□□□ʡ□: 'checkpoints/multi30k-en2de/clip/04041808_0.5klmulti_32_sd_ran0+0.1beforeimgotlossvishal_release\\gate.txt'

Have you ever been in this situation?

**Comment by Christina0717** [comment]
The reason of the [WinError 32] Error may be that the file is occupied by other programs or the permission to operate the files is denied. Please make sure that you have the permission to create a directory and save the files during the training process. You may want to run this script under Linux environment to see if this problem still exits.

**Comment by dana-niu** [comment]
OK，thank you



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/04/2024 20:57 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ictnlp/SAMMT] garbled codes (Issue #2) |

The reason of the [WinError 32] Error may be that the file is occupied by other programs or the permission to operate the files is denied. Please make sure that you have the permission to create a directory and save the files during the training process. You may want to run this script under Linux environment to see if this problem still exits.
